#!/bin/sh

set -e

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
if ! [ -z "$FILES" ]; then
  URL="$(cat .git-hooks/url.txt)"
  if echo "$FILES" | xargs grep "${URL}"; then
    echo "Remove URL from file before commit"
    exit 1
  fi
fi

if ! [ -x "$(command -v prettier)" ]; then
  echo 'Error: Prettier is not installed' && exit 1
else
  FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.md" "*.yml" "*.yaml" | sed 's| |\\ |g')
  if ! [ -z "$FILES" ]; then
    echo "Running Prettier..."

    # Prettify all selected files
    echo "$FILES" | xargs prettier --write --no-bracket-spacing

    # Add back the modified/prettified files to staging
    echo "$FILES" | xargs git add
  fi
fi

if ! [ -x "$(command -v yamllint)" ]; then
  echo 'Error: yamllint is not installed' >&2
else
  FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.yml" "*.yaml" | sed 's| |\\ |g')
  if ! [ -z "$FILES" ]; then
    echo "Running yamllint..."
    
    # Run yamllint
    echo "$FILES" | xargs yamllint
  fi
fi
