version: "3.8"

services:
  coder:
    container_name: coder
    hostname: code-server
    image: coder:latest
    build: .
    restart: unless-stopped
    user: "1000"
    expose:
      - "8080"
    volumes:
      - ./config:/home/coder/.local/share/code-server # config dir with all extensions and settings
      - ./config:/home/coder/.config/code-server # for Syncing extension
      - ./wakatime.cfg:/home/coder/.wakatime.cfg
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${HOME}/workspace:/home/coder/workspace
      - ${HOME}/docker:/home/coder/docker
      - ${HOME}/Dotfiles:/home/coder/Dotfiles
      - ${HOME}/.gitconfig:/home/coder/.gitconfig
      - ${HOME}/.ssh:/home/coder/.ssh:ro
      - ${HOME}/.gnupg:/home/coder/.gnupg
      - ${HOME}/.password-store:/home/coder/.password-store
      - ${HOME}/home-assistant/config:/home/coder/home-assistant
    environment:
      - PASSWORD
      - DOCKER_USER=${USER}
    labels:
      - "traefik.enable=true"

networks:
  default:
    external:
      name: docker
