version: "3.8"

services:
  coder:
    container_name: coder
    hostname: code-server
    image: coder:latest
    build: .
    restart: unless-stopped
    expose:
      - "8080"
    volumes:
      - ./config:/home/coder/.local/share/code-server
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${HOME}/.ssh:/home/coder/.ssh:ro
      - ${HOME}/workspace:/home/coder/workspace
      - ${HOME}/docker:/home/coder/docker
      - ${HOME}/home-assistant:/home/coder/home-assistant
    environment:
      - PASSWORD
    labels:
      - "traefik.enable=true"

networks:
  default:
    external:
      name: docker
