version: "3.7"

services:
  coder:
    container_name: coder
    hostname: code-server
    build: .
    restart: unless-stopped
    entrypoint:
      - "dumb-init"
      - "fixuid"
      - "code-server"
      - "--host"
      - "0.0.0.0"
      - --disable-telemetry
      - --disable-ssh
      - --disable-updates
    expose:
      - "8080"
    volumes:
      - "./config:/home/coder/.local/share/code-server"
      - "${HOME}/.gitconfig:/home/coder/.gitconfig:ro"
      - "${HOME}/.git-credentials:/home/coder/.git-credentials:ro"
      - "${HOME}/.ssh:/home/coder/.ssh:ro"
      - "${HOME}/workspace:/home/coder/workspace"
      - "${HOME}/docker:/home/coder/docker"
      - "${HOME}/home-assistant:/home/coder/home-assistant"
      - "${HOME}/grafterburner:/home/coder/grafterburner"
    environment:
      PASSWORD: ${PASSWORD}
      DOCKER_HOST: "tcp://socket-proxy:2375"
    labels:
      - "traefik.enable=true"

networks:
  default:
    external:
      name: docker
