version: "3.7"

services:
  code-server:
    container_name: code-server
    image: "codercom/code-server:latest"
    entrypoint:
      - "dumb-init"
      - "code-server"
      - "--host"
      - "0.0.0.0"
      - "--cert"
    ports:
      - "8070:8080"
    volumes:
      - "./config:/home/coder/.local/share/code-server"
      - "${HOME}/.gitconfig:/home/coder/.gitconfig"
      - "${HOME}/.ssh:/home/coder/.ssh"
      - "${HOME}/docker:/home/coder/docker"
    environment:
      PASSWORD: ${CODE_SERVER_PASSWORD}
