version: "3.8"

services:
  coder:
    container_name: coder
    hostname: code-server
    image: coder:latest
    build: .
    restart: unless-stopped
    expose:
      - "8080"
    volumes:
      - ./config:/home/coder/.local/share/code-server
      - ./.wakatime.cfg:/home/coder/wakatime.cfg
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${HOME}/workspace:/home/coder/workspace
      - ${HOME}/docker:/home/coder/docker
      - ${HOME}/.ssh:/home/coder/.ssh:ro
      - ${HOME}/.gnupg:/home/coder/.gnupg
      - ${HOME}/.gitconfig:/home/coder/.gitconfig
      - ${HOME}/.password-store:/home/coder/.password-store
      - type: bind
        source: ${HOME}/home-assistant
        target: /home/coder/home-assistant
        bind:
          propagation: shared # needed for cifs
    environment:
      - PASSWORD
    labels:
      - "traefik.enable=true"

networks:
  default:
    external:
      name: docker
