# https://github.com/LINKIWI/orion-docker
version: "3.8"

services:
  orion-web:
    container_name: orion-web
    restart: unless-stopped
    build:
      context: web
      args:
        - ORION_SERVER_URL
        - MAPBOX_API_TOKEN
    expose:
      - "8080"
    environment:
      - ORION_SERVER_URL
      - MAPBOX_API_TOKEN
    depends_on:
      - orion-server
    labels:
      - "traefik.enable=true"
      - "containermon.enable=true"

  orion-server:
    container_name: orion-server
    restart: unless-stopped
    build:
      context: server
    expose:
      - "8080"
    environment:
      - DATABASE_HOST=orion-db
      - DATABASE_PORT=3306
      - DATABASE_NAME=orion
      - DATABASE_USER=root
      - DATABASE_PASSWORD
      - FRONTEND_URL
      - MAPBOX_ACCESS_TOKEN
    depends_on:
      - orion-db
    labels:
      - "traefik.enable=true"
      - "containermon.enable=true"

  orion-db:
    container_name: orion-db
    image: mariadb:10.5
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=orion
    labels:
      - "containermon.enable=true"

networks:
  default:
    external:
      name: docker
