# https://docs.docker.com/reference/compose-file/

services:
  app:
    container_name: app
    # avoid latest, makes finding out the version annoying
    image: dev/app:v1.0.0
    # build: .
    extends:
      file: ../base.yml
      service: base
    # healthcheck:
    # test: ["CMD", "pgrep", "process_name"]
    ports:
      - "8080:8080" # HOST_PORT:CONTAINER_PORT
    expose:
      - "8000"
    # remember to update any backup exclusions
    volumes:
      - ./data:/app/data # HOST_PATH:CONTAINER_PATH
    environment:
      - VAR=VAL
      - SECRET_ENV_VAR # from .env file
    depends_on:
      - db
    labels:
      - "com.example.enable=true"

include:
  - ../network.yml
