version: "3.7"

services:
  heimdall:
    container_name: heimdall
    image: linuxserver/heimdall:latest
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - "./config:/config"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    labels:
      - "diun.enable=true"
      - "traefik.enable=true"

networks:
  default:
    external:
      name: docker
