# https://github.com/filebrowser/filebrowser
version: "3.8"

services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:latest
    restart: unless-stopped
    user: "1000"
    expose:
      - "8080"
    volumes:
      - ./.filebrowser.json:/.filebrowser.json
      - ${HOME}:/data/home
      - /mnt/hdd:/data/hdd
      - ./data:/data
      - ./db:/db
    labels:
      - "traefik.enable=true"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.services.filebrowser-filebrowser.loadbalancer.server.port=8080"
    healthcheck:
      disable: true # https://github.com/filebrowser/filebrowser/pull/1409

networks:
  default:
    external:
      name: docker
