# https://github.com/filebrowser/filebrowser

services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:v2
    extends:
      file: ../base.yml
      service: base
    user: "1000"
    expose:
      - "80"
    volumes:
      - ./app:/database
      - ./app:/config
      - ${HOME}:/srv
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.filebrowser-filebrowser.loadbalancer.server.port=80"
      - "wud.tag.include=^v\\d+$$"
      - "wud.watch.digest=true"

include:
  - ../network.yml
