# https://github.com/filebrowser/filebrowser

services:
  filebrowser:
    container_name: filebrowser
    image: filebrowser/filebrowser:v2
    restart: unless-stopped
    user: "1000"
    expose:
      - "80"
    volumes:
      - ./app:/database
      - ./app:/config
      - ${HOME}:/srv
    labels:
      - "traefik.enable=true"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.services.filebrowser-filebrowser.loadbalancer.server.port=80"
    healthcheck:
      disable: true # https://github.com/filebrowser/filebrowser/pull/1409

networks:
  default:
    external: true
    name: docker
