# https://hub.docker.com/r/duplicati/duplicati
version: "3.8"

services:
  duplicati:
    container_name: duplicati
    hostname: duplicati
    image: duplicati/duplicati:latest
    restart: unless-stopped
    command: # Check cmd from https://hub.docker.com/r/duplicati/duplicati/tags if this changes
      - "/usr/bin/duplicati-server"
      - "--webservice-port=8200"
      - "--webservice-interface=any"
      - "--webservice-allowed-hostnames=*" # Needed for Traefik to work
    expose:
      - "8200"
    volumes:
      - /mnt/hdd/Backup:/destination
      - ${HOME}:/source
      - ./data/:/data
    labels:
      - "traefik.enable=true"
      - "diun.enable=true"

networks:
  default:
    external:
      name: docker
