# https://github.com/RafhaanShah/Container-Mon

services:
  container-mon:
    container_name: container-mon
    image: ghcr.io/rafhaanshah/container-mon:v1
    extends:
      file: ../base.yml
      service: base
    environment:
      - CONTAINERMON_NOTIFICATION_URL
      # - CONTAINERMON_USE_LABELS=true
      - DOCKER_HOST=tcp://socket-proxy:2375
    labels:
      - "wud.tag.include=^v\\d+$$"
      - "wud.watch.digest=true"

include:
  - ../network.yml
