# https://github.com/RafhaanShah/Container-Mon

services:
  container-mon:
    container_name: container-mon
    image: ghcr.io/rafhaanshah/container-mon:v1.0.5
    restart: unless-stopped
    environment:
      - CONTAINERMON_NOTIFICATION_URL
      # - CONTAINERMON_USE_LABELS=true
      - DOCKER_HOST=tcp://socket-proxy:2375

networks:
  default:
    external: true
    name: docker
