# https://github.com/RafhaanShah/Net-Mon

services:
  net-mon:
    container_name: net-mon
    image: ghcr.io/rafhaanshah/net-mon:v1
    extends:
      file: ../base.yml
      service: base
    network_mode: host # needed for nmap
    volumes:
      - ./results.json:/app/results.json
    environment:
      - NETMON_NOTIFICATION
      - NETMON_SUBNET=192.168.1.0/24
      - NETMON_MINUTES=30
    tags:
      - "wud.tag.include=^v\\d+$$"
      - "wud.watch.digest=true"
