{
 "title": "MSI Afterburner",
 "description": "Shows stats from MSI Afterburner",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Prometheus", "label": "Prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"collectd.rafs_pc.curl_xml-afterburner.gauge-CPU_usage\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "{__name__=\"collectd.rafs_pc.curl_xml-afterburner.gauge-GPU_usage\"}",
     "legendFormat": "GPU"
    }
   ]
  },
  {
   "title": "GPU Limiting Factor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"collectd.rafs_pc.curl_xml-afterburner.gauge-No_load_limit\"}",
     "legendFormat": "No Load"
    },
    {
     "expr": "{__name__=\"collectd.rafs_pc.curl_xml-afterburner.gauge-Power_limit\"}",
     "legendFormat": "Power"
    },
    {
     "expr": "{__name__=\"collectd.rafs_pc.curl_xml-afterburner.gauge-Temp_limit\"}",
     "legendFormat": "Temp"
    },
    {
     "expr": "{__name__=\"collectd.rafs_pc.curl_xml-afterburner.gauge-Voltage_limit\"}",
     "legendFormat": "Voltage"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"collectd.rafs_pc.curl_xml-afterburner.gauge-Framerate\"}",
     "legendFormat": "FPS"
    }
   ]
  },
  {
   "title": "FPS / Frametime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"collectd.rafs_pc.curl_xml-afterburner.gauge-Framerate\"}",
     "legendFormat": "FPS"
    },
    {
     "expr": "{__name__=\"collectd.rafs_pc.curl_xml-afterburner.gauge-Frametime\"}",
     "legendFormat": "Frametime"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"collectd.rafs_pc.curl_xml-afterburner.gauge-CPU_temperature\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "{__name__=\"collectd.rafs_pc.curl_xml-afterburner.gauge-GPU_temperature\"}",
     "legendFormat": "GPU"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=\"collectd.rafs_pc.curl_xml-afterburner.gauge-Frametime\"}",
     "legendFormat": "Frametime"
    }
   ]
  },
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"collectd.rafs_pc.curl_xml-afterburner.gauge-CPU_usage\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "{__name__=\"collectd.rafs_pc.curl_xml-afterburner.gauge-GPU_usage\"}",
     "legendFormat": "GPU"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"collectd.rafs_pc.curl_xml-afterburner.gauge-CPU_temperature\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "{__name__=\"collectd.rafs_pc.curl_xml-afterburner.gauge-GPU_temperature\"}",
     "legendFormat": "GPU"
    }
   ]
  },
  {
   "title": "Clockspeeds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"collectd.rafs_pc.curl_xml-afterburner.gauge-CPU_clock\"}*1000000",
     "legendFormat": "CPU"
    },
    {
     "expr": "{__name__=\"collectd.rafs_pc.curl_xml-afterburner.gauge-Core_clock\"}*1000000",
     "legendFormat": "GPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"collectd.rafs_pc.curl_xml-afterburner.gauge-RAM_usage\"}",
     "legendFormat": "RAM"
    },
    {
     "expr": "{__name__=\"collectd.rafs_pc.curl_xml-afterburner.gauge-Memory_usage\"}",
     "legendFormat": "VRAM"
    }
   ]
  },
  {
   "title": "Voltage / Memory Clock",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"collectd.rafs_pc.curl_xml-afterburner.gauge-Memory_clock\"}*1000000",
     "legendFormat": "Memory Clock"
    },
    {
     "expr": "{__name__=\"collectd.rafs_pc.curl_xml-afterburner.gauge-GPU_voltage\"}",
     "legendFormat": "Voltage"
    }
   ]
  },
  {
   "title": "GPU Fans",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"collectd.rafs_pc.curl_xml-afterburner.gauge-Fan_speed\"}",
     "legendFormat": "Fan 1 Speed"
    },
    {
     "expr": "{__name__=\"collectd.rafs_pc.curl_xml-afterburner.gauge-Fan_speed_2\"}",
     "legendFormat": "Fan 2 Speed"
    },
    {
     "expr": "{__name__=\"collectd.rafs_pc.curl_xml-afterburner.gauge-Fan_tachometer\"}",
     "legendFormat": "Fan 1 RPM"
    },
    {
     "expr": "{__name__=\"collectd.rafs_pc.curl_xml-afterburner.gauge-Fan_tachometer_2\"}",
     "legendFormat": "Fan 2 RPM"
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "{__name__=\"collectd.rafs_pc.curl_xml-afterburner.gauge-CPU_power\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "{__name__=\"collectd.rafs_pc.curl_xml-afterburner.gauge-Power\"}",
     "legendFormat": "GPU"
    }
   ]
  }
 ]
}