{
 "title": "OPNsense",
 "description": "Host monitoring dashboard with data from Prometheus sent by Node Exporter.",
 "tags": [
  "opnsense",
  "nodeexporter",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "source", "label": "Data Source", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(node_uname_info,instance)"
    }
   },
   {
    "name": "rate",
    "label": "Rate",
    "query": "1s,10s,30s,1m,2m,5m,10m,1h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(${__to} / 1000) - (node_boot_time_seconds{instance=~\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"$node\"}) by (cpu))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (instance, mountpoint) (node_filesystem_size_bytes{instance=~\"$node\",mountpoint=\"/\"}) - max by (instance, mountpoint) (node_filesystem_free_bytes{instance=~\"$node\",mountpoint=\"/\"}) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (instance, mountpoint) (node_filesystem_size_bytes{instance=~\"$node\",mountpoint=\"/\"}) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "(max by (instance, mountpoint) (node_filesystem_size_bytes{instance=~\"$node\",mountpoint=\"/\"}) - max by (instance, mountpoint) (node_filesystem_free_bytes{instance=~\"$node\",mountpoint=\"/\"})) / (max by (instance, mountpoint) (node_filesystem_size_bytes{instance=~\"$node\",mountpoint=\"/\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_active_bytes{instance=~\"$node\"} + node_memory_wired_bytes{instance=~\"$node\"} + node_memory_laundry_bytes{instance=~\"$node\"}) / node_memory_size_bytes{instance=~\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_size_bytes{instance=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_swap_used_bytes{instance=~\"$node\"} / node_memory_swap_size_bytes{instance=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_swap_size_bytes{instance=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Internet Latency",
   "type": "timeseries",
   "description": "Uses external metrics from netdata ping -> InfluxDB.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "ping_average_response_ms", "legendFormat": "1.1.1.1" }
   ]
  },
  {
   "title": "Network",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (instance, device) (node_network_receive_bytes_total{instance=~\"$node\"}) > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (instance, device) (node_network_transmit_bytes_total{instance=~\"$node\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 - avg by(instance)(rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$node\"}[$rate])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by (instance) (node_cpu_temperature_celsius{instance=~\"$node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "((node_memory_active_bytes{instance=~\"$node\"} + node_memory_wired_bytes{instance=~\"$node\"} + node_memory_laundry_bytes{instance=~\"$node\"}) / node_memory_size_bytes{instance=~\"$node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "node_memory_swap_used_bytes{instance=~\"$node\"} / node_memory_swap_size_bytes{instance=~\"$node\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Network In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(rate(node_network_receive_bytes_total{instance=~\"$node\"}[$rate]))>0",
     "legendFormat": "{{instance}}: {{device}}"
    }
   ]
  },
  {
   "title": "Network Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(rate(node_network_transmit_bytes_total{instance=~\"$node\"}[$rate]))>0",
     "legendFormat": "{{instance}}: {{device}}"
    }
   ]
  },
  {
   "title": "Packets In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(rate(node_network_receive_packets_total{instance=~\"$node\"}[$rate]))>0",
     "legendFormat": "{{instance}}: {{device}}"
    }
   ]
  },
  {
   "title": "Packets Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "(rate(node_network_transmit_packets_total{instance=~\"$node\"}[$rate]))>0",
     "legendFormat": "{{instance}}: {{device}}"
    }
   ]
  },
  {
   "title": "Dropped In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(rate(node_network_receive_drop_total{instance=~\"$node\"}[$rate]))",
     "legendFormat": "{{instance}}: {{device}}"
    }
   ]
  },
  {
   "title": "Dropped Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(rate(node_network_transmit_drop_total{instance=~\"$node\"}[$rate]))",
     "legendFormat": "{{instance}}: {{device}}"
    }
   ]
  },
  {
   "title": "Errors In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(rate(node_network_receive_errs_total{instance=~\"$node\"}[$rate]))",
     "legendFormat": "{{instance}}: {{device}}"
    }
   ]
  },
  {
   "title": "Errors Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(rate(node_network_transmit_errs_total{instance=~\"$node\"}[$rate]))",
     "legendFormat": "{{instance}}: {{device}}"
    }
   ]
  }
 ]
}