{
 "title": "Proxmox",
 "description": "Proxmox Dashboard from Prometheus data source for data ingested from Proxmox Metrics Server -> InfluxDB (i.e. VictoriaMetrics).",
 "tags": [
  "proxmox",
  "influxdb",
  "prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "source", "label": "Data Source", "query": "prometheus" },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(system_uptime{object=\"nodes\"},host)"
    }
   },
   {
    "name": "vm",
    "label": "VM",
    "query": {
     "query": "label_values(system_uptime{object!=\"nodes\", nodename=~\"$node\"},host)"
    }
   },
   {
    "name": "rate",
    "label": "Rate",
    "query": "1s,10s,30s,1m,2m,5m,10m,1h,6h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_uptime{host=~\"$node\", object=\"nodes\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpustat_cpus{host=~\"$node\", object=\"nodes\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (vmid)\n  (system_uptime{nodename=~\"$node\", object!=\"node\", vmid=~\"[0-9]+\"} > 0)\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VMs",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "targets": [
    {
     "expr": "max by(host, vmid, object, nodename) (system_uptime{nodename=~\"$node\", object!=\"nodes\", host=~\"$vm\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (host, nodename) (system_used{object=\"storages\",nodename=~\"$node\",type=~\".+\"}) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (host, nodename)(system_total{object=\"storages\",nodename=~\"$node\",type=~\".+\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "(max by (host, nodename) (system_used{object=\"storages\",nodename=~\"$node\",type=~\".+\"})) / (max by (host, nodename)(system_total{object=\"storages\",nodename=~\"$node\",type=~\".+\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_memtotal{host=~\"$node\", object=\"nodes\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_memused{host=~\"$node\", object=\"nodes\"} / memory_memtotal{host=~\"$node\", object=\"nodes\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_swaptotal{host=~\"$node\", object=\"nodes\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_swapused{host=~\"$node\", object=\"nodes\"} / memory_swaptotal{host=~\"$node\", object=\"nodes\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "cpustat_cpu{host=~\"$node\", object=\"nodes\"}",
     "legendFormat": "Usage {{host}}"
    },
    {
     "expr": "cpustat_wait{host=~\"$node\", object=\"nodes\"}",
     "legendFormat": "I/O Wait: {{host}} "
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(nics_receive{host=~\"$node\", object=\"nodes\", instance=~\"en.+\"}[$rate]) > 0",
     "legendFormat": "In: {{host}} {{instance}}"
    },
    {
     "expr": "rate(nics_transmit{host=~\"$node\", object=\"nodes\", instance=~\"en.+\"}[1m]) > 0",
     "legendFormat": "Out: {{host}} {{instance}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "Uses external metrics from lm-sensors -> collectd -> Graphite.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "collectd.rafs_proxmox.sensors\\-coretemp\\-isa\\-\\0\\0\\0\\0.temperature\\-temp1",
     "legendFormat": "$node"
    }
   ]
  },
  {
   "title": "Fan",
   "type": "timeseries",
   "description": "Uses external metrics from lm-sensors -> collectd -> Graphite.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "collectd.rafs_proxmox.sensors\\-it8728\\-isa\\-0a40.fanspeed\\-fan1",
     "legendFormat": "$node"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "memory_memused{host=~\"$node\", object=\"nodes\"} / memory_memtotal{host=~\"$node\", object=\"nodes\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "memory_swapused{host=~\"$node\", object=\"nodes\"} / memory_swaptotal{host=~\"$node\", object=\"nodes\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "VM CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu{nodename=~\"$node\", object!=\"nodes\", host=~\"$vm\"} > 0",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "VM Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(system_mem{nodename=~\"$node\",host=~\"$vm\"} / system_maxmem{nodename=~\"$node\",host=~\"$vm\"}) > 0 ",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "VM Balloon",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(ballooninfo_free_mem{nodename=~\"$node\",host=~\"$vm\"}) > 0 ",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "VM Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(system_mem{nodename=~\"$node\",host=~\"$vm\"}) > 0 ",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "VM Net In",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(system_netin{nodename=~\"$node\", host=~\"$vm\"}[$rate]) > 0",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "VM Net Out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(system_netout{nodename=~\"$node\", host=~\"$vm\"}[$rate]) > 0",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "VM Disk Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(system_diskread{nodename=~\"$node\", host=~\"$vm\"}[$rate]) > 0",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "VM Disk Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(system_diskwrite{nodename=~\"$node\", host=~\"$vm\"}[$rate]) > 0",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}