# https://github.com/containous/traefik

services:
  traefik:
    container_name: traefik
    image: traefik:v2.10.3
    extends:
      file: ../base.yml
      service: base
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./acme.json:/etc/traefik/acme.json
      - ./config:/etc/traefik/config
    environment:
      - DUCKDNS_TOKEN

include:
  - ../network.yml
