version: "3.8"

services:
  traefik:
    container_name: traefik
    image: traefik:v2.2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./acme.json:/etc/traefik/acme.json
      - ./config:/etc/traefik/config
    environment:
      - DUCKDNS_TOKEN
    labels:
      - "diun.enable=true"
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  default:
    external:
      name: docker
