version: "3.7"

services:
  grafana:
    container_name: grafana
    image: "grafana/grafana:latest"
    restart: unless-stopped
    user: "1000"
    expose:
      - "3000"
    volumes:
      - "./storage:/var/lib/grafana"
      - "./datasources:/etc/grafana/provisioning/datasources"
      - "./dashboards:/etc/grafana/provisioning/dashboards"
    environment:
      - "GF_AUTH_DISABLE_LOGIN_FORM=true"
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
      - "GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
    labels:
      - "diun.enable=true"
      - "traefik.enable=true"

networks:
  default:
    external:
      name: docker
