# https://github.com/grafana/grafana
version: "3.8"

services:
  grafana:
    container_name: grafana
    image: "grafana/grafana:10.1.10"
    restart: unless-stopped
    user: "1000"
    expose:
      - "3000"
    volumes:
      - ./storage:/var/lib/grafana
      - ./datasources:/etc/grafana/provisioning/datasources
      - ./dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=1s
      - GF_SERVER_ROOT_URL
    labels:
      # - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "containermon.enable=true"

  # loki:
  #   container_name: loki
  #   image: grafana/loki:2.0.0
  #   command: -config.file=/etc/loki/config.yaml
  #   volumes:
  #     - ./loki:/loki
  #     - ./loki.yaml:/etc/loki/config.yaml

  # promtail:
  #   container_name: promtail
  #   image: grafana/promtail:2.0.0
  #   command: -config.file=/etc/promtail/config.yml
  #   volumes:
  #     - ./promtail:/positions
  #     - ./promtail.yml:/etc/promtail/config.yml
  #     - /var/lib/docker/containers:/var/lib/docker/containers
  #   depends_on:
  #     - loki

networks:
  default:
    external:
      name: docker
