# https://grafana.com/docs/loki/latest/clients/promtail/configuration/
server:
  http_listen_address: 0.0.0.0
  http_listen_port: 9080
  log_level: warn

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /positions/positions.yaml

scrape_configs:
  # - job_name: system
  #   static_configs:
  #   - targets:
  #       - localhost
  #     labels:
  #       job: varlogs
  #       __path__: /var/log/*log

  # https://github.com/grafana/loki/issues/333
  # https://gist.github.com/ruanbekker/c6fa9bc6882e6f324b4319c5e3622460
  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      - json:
          expressions:
            output: log
            stream: stream
            attrs:
      - json:
          expressions:
            tag:
          source: attrs
      - regex:
          expression: (?P<container_name>(?:[^|]*[^|]))
          source: tag
      - timestamp:
          format: RFC3339Nano
          source: time
      - labels:
          # tag:
          stream:
          container_name:
      - output:
          source: output
