version: "3.7"

services:
  diun:
    container_name: diun
    image: crazymax/diun:latest
    network_mode: bridge
    restart: always
    volumes:
      - "./data:/data"
      - "./diun.yml:/diun.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - "TZ=Europe/London"
      - "LOG_LEVEL=info"
      - "LOG_JSON=true"
    