# https://github.com/crazy-max/diun
version: "3.8"

services:
  diun:
    container_name: diun
    image: crazymax/diun:latest
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./diun.yml:/diun.yml:ro
      - ./file.yml:/file.yml:ro
    environment:
      - TZ=Europe/London
      - LOG_LEVEL=info
      - LOG_JSON=true
      - DIUN_NOTIF_TELEGRAM_TOKEN
      - DIUN_NOTIF_TELEGRAM_CHATIDS
    labels:
      - "diun.enable=true"
      - "containermon.enable=true"

networks:
  default:
    external:
      name: docker
