version: "3.8"

services:
  diun:
    container_name: diun
    image: crazymax/diun:latest
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./diun.yml:/diun.yml:ro
    environment:
      - TZ=Europe/London
      - LOG_LEVEL=info
      - LOG_JSON=true
    labels:
      - "diun.enable=true"

networks:
  default:
    external:
      name: docker
