# https://github.com/garethgeorge/backrest

services:
  backrest:
    container_name: backrest
    image: garethgeorge/backrest:v1
    extends:
      file: ../base.yml
      service: base
    # healthcheck:
    #   test: ["CMD", "/usr/bin/curl", "-s", "-I", "localhost:9898"]
    expose:
      - "9898"
    volumes:
      - ./data:/data
      - ./config:/config
      - ./cache:/cache
      - ./tmp:/tmp
      # - ./backrest/rclone:/root/.config/rclone # Mount for rclone config (needed when using rclone remotes)
      - ${HOME}:/userdata # Mount local paths to backup
      # - /path/to/local/repos:/repos # Mount local repos (optional for remote storage)
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=Europe/London
    labels:
      - "traefik.enable=true"
      - "wud.tag.include=^v\\d+$$"
      - "wud.watch.digest=true"

include:
  - ../network.yml
