# https://github.com/garethgeorge/backrest

services:
  backrest:
    container_name: backrest
    image: garethgeorge/backrest:v1
    restart: unless-stopped
    expose:
      - "9898"
    volumes:
      - ./data:/data
      - ./config:/config
      - ./cache:/cache
      - ./tmp:/tmp
      # - ./backrest/rclone:/root/.config/rclone # Mount for rclone config (needed when using rclone remotes)
      - ${HOME}:/userdata # Mount local paths to backup
      # - /path/to/local/repos:/repos # Mount local repos (optional for remote storage)
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=Europe/London
    labels:
      - "traefik.enable=true"

networks:
  default:
    external: true
    name: docker
