# https://github.com/RafhaanShah/Reddit-Post-Notifier

services:
  reddit-post-notifier:
    container_name: reddit-post-notifier
    image: ghcr.io/rafhaanshah/reddit-post-notifier:v1.0.2
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml

networks:
  default:
    external: true
    name: docker
