# https://github.com/RafhaanShah/Reddit-Post-Notifier

services:
  reddit-post-notifier:
    container_name: reddit-post-notifier
    image: ghcr.io/rafhaanshah/reddit-post-notifier:v1.0.2
    extends:
      file: ../base.yml
      service: base
    volumes:
      - ./config.yaml:/app/config.yaml

include:
  - ../network.yml
