# https://github.com/RafhaanShah/Reddit-Post-Notifier
version: "3.8"

services:
  reddit-post-notifier:
    container_name: reddit-post-notifier
    image: ghcr.io/rafhaanshah/reddit-post-notifier:latest
    restart: unless-stopped
    volumes:
      - ./config.yaml:/app/config.yaml
    labels:
      - "containermon.enable=true"
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  default:
    external:
      name: docker
