# https://github.com/RafhaanShah/Reddit-Post-Notifier

services:
  reddit-post-notifier:
    container_name: reddit-post-notifier
    image: ghcr.io/rafhaanshah/reddit-post-notifier:v2.0.1
    extends:
      file: ../base.yml
      service: base
    volumes:
      - ./config.yaml:/app/config.yaml
    labels:
      - "wud.tag.include=^v\\d+\\.\\d+\\.\\d+$$"

include:
  - ../network.yml
