version: "3.8"

services:
  tinyfilemanager:
    container_name: tinyfilemanager
    image: tinyfilemanager:latest
    build: .
    restart: unless-stopped
    user: "1000"
    expose:
      - "8080"
    volumes:
      - ./data:/web/data
      - ${HOME}:/web/data/home
      - /mnt/hdd:/web/data/hdd
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.tfm-auth.basicauth.users=raf:${PASSWORD}"
      - "traefik.http.routers.http-tinyfilemanager-tinyfilemanager.middlewares=tfm-auth@docker"

networks:
  default:
    external:
      name: docker
