version: "3.8"

services:
  tinyfilemanager:
    container_name: tinyfilemanager
    image: tinyfilemanager:latest
    build: .
    restart: unless-stopped
    user: "1000"
    expose:
      - "8080"
    volumes:
      - ./data:/web/data
    labels:
      - "traefik.enable=true"

networks:
  default:
    external:
      name: docker
