# https://github.com/nirui/sshwifty

services:
  sshwifty:
    container_name: sshwifty
    image: niruix/sshwifty:0.3.25-beta-release
    user: "nobody:nobody"
    extends:
      file: ../base.yml
      service: base
    # healthcheck:
    #   test: ["CMD", "/usr/bin/wget", "--spider", "--quiet", "--tries=1", "localhost:8182/sshwifty/socket/verify"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    expose:
      - "8182"
    volumes:
      - ./sshwifty.conf.json:/sshwifty.conf.json
    environment:
      - SSHWIFTY_CONFIG=/sshwifty.conf.json
    labels:
      - "traefik.enable=true"
      - "wud.tag.include=^\\d+\\.\\d+\\.\\d+.*$$"
      - "wud.tag.transform=^(\\d+\\.\\d+\\.\\d+).*$$ => $$1"

include:
  - ../network.yml
