# https://github.com/owntracks/frontend
# https://github.com/owntracks/recorder

services:
  owntracks-frontend:
    container_name: owntracks-frontend
    image: owntracks/frontend:2.15.3
    extends:
      file: ../base.yml
      service: base
    # healthcheck:
    #   test: ["CMD", "/usr/bin/curl", "-s", "-I", "localhost:80"]
    expose:
      - "80"
    environment:
      - SERVER_HOST=owntracks-recorder
      - SERVER_PORT=8083
    depends_on:
      - owntracks-recorder
    labels:
      - "traefik.enable=true"

  owntracks-recorder:
    container_name: owntracks-recorder
    hostname: owntracks-recorder
    image: owntracks/recorder:1.0.0
    extends:
      file: ../base.yml
      service: base
    # healthcheck:
    #   test: ["CMD", "/usr/bin/curl", "-s", "localhost:8083/api/0/monitor"]
    expose:
      - "8083"
    volumes:
      - ./data:/store
      - ./config:/config
    environment:
      - OTR_PORT=0 # disable mqtt if 0
      - OTR_HOST=owntracks-mqtt
      - OTR_HTTPPORT=8083
      - OTR_STORAGEDIR=/store
      # - OTR_GEOKEY
      # - OTR_BROWSERAPIKEY
    labels:
      - "traefik.enable=true"

# owntracks-mqtt:
#   container_name: owntracks-mqtt
#   image: eclipse-mosquitto:2
#   ports:
#     - "1883:1883"
#   volumes:
#     - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

include:
  - ../network.yml
