# https://github.com/11notes/docker-socket-proxy
# alt: https://github.com/linuxserver/docker-socket-proxy
# alt: https://github.com/Tecnativa/docker-socket-proxy

services:
  socket-proxy:
    container_name: socket-proxy
    image: ghcr.io/11notes/socket-proxy:2
    read_only: true
    user: "0:988"
    extends:
      file: ../base.yml
      service: base
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - socket-proxy.run:/run/proxy
    environment:
      - TZ=Europe/London
    labels:
      - "wud.tag.include=^\\d+$$"
      - "wud.watch.digest=true"

volumes:
  socket-proxy.run:

include:
  - ../network.yml
