version: "3.7"

services:
  socket-proxy:
    container_name: socket-proxy
    image: tecnativa/docker-socket-proxy
    restart: unless-stopped
    expose:
      - "2375"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      CONTAINERS: 1
      IMAGES: 1
    labels:
      - "diun.enable=true"

networks:
  default:
    external:
      name: docker
