# https://github.com/Tecnativa/docker-socket-proxy

services:
  socket-proxy:
    container_name: socket-proxy
    image: ghcr.io/tecnativa/docker-socket-proxy:0.2
    restart: unless-stopped
    expose:
      - "2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./haproxy.cfg.template:/usr/local/etc/haproxy/haproxy.cfg.template
      - ./server-state:/var/lib/haproxy/server-state
    environment:
      - LOG_LEVEL=notice
      - CONTAINERS=1
      - IMAGES=1
      - INFO=1
      - EVENTS=1
    labels:
      - "diun.enable=true"
      - "containermon.enable=true"

networks:
  default:
    external: true
    name: docker
