# https://hub.docker.com/_/adminer
version: "3.8"

services:
  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  default:
    external:
      name: docker
