services:
  collectd:
    container_name: collectd
    image: collectd:1.0.0
    build: .
    extends:
      file: ../base.yml
      service: base
    volumes:
      - ./collectd.conf:/etc/collectd/collectd.conf
    external_links:
      - victoriametrics
    logging:
      driver: none

include:
  - ../network.yml
