services:
  collectd:
    container_name: collectd
    image: collectd:1.0.0
    build: .
    restart: unless-stopped
    volumes:
      - ./collectd.conf:/etc/collectd/collectd.conf
    external_links:
      - victoriametrics
    logging:
      driver: none

networks:
  default:
    external: true
    name: docker
