version: "3.8"

services:
  collectd:
    container_name: collectd
    image: collectd:latest
    build: .
    restart: unless-stopped
    volumes:
      - ./collectd.conf:/etc/collectd/collectd.conf
    external_links:
      - victoriametrics
    logging:
      driver: none
    labels:
      - "containermon.enable=true"

networks:
  default:
    external:
      name: docker
