services:
  collectd:
    container_name: collectd
    image: collectd:1.0.0
    build: .
    extends:
      file: ../base.yml
      service: base
    volumes:
      - ./collectd.conf:/etc/collectd/collectd.conf
    # noisy spam when PC is offline
    logging:
      driver: none
    labels:
      - wud.watch=false

include:
  - ../network.yml
