apiVersion: 1

datasources:
  - name: Elasticsearch-Netflow
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "[filebeat-*-netflow-]YYYY.MM.DD"
    editable: true
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: 70
