version: "3.8"

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    restart: unless-stopped
    expose:
      - "9200"
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    environment:
      - ES_JAVA_OPTS=-Xmx512m -Xms512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    labels:
      - "traefik.enable=true"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.6.2
    restart: unless-stopped
    expose:
      - "5601"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - elasticsearch
    labels:
      - "traefik.enable=true"

  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.6.2
    restart: unless-stopped
    ports:
      - "514:514/udp" # Syslog UDP
      - "2055:2055/udp" # Netflow
      - "6514:6514" # Syslog TCP
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./filebeat:/usr/share/filebeat/config:ro
      - ./test.log:/logs/test.log:ro # Test Log File
      - ./../pihole/pihole.log:/logs/pihole.log:ro # Pi-Hole Logs
      - /var/lib/docker:/var/lib/docker:ro # Docker Logs
    depends_on:
      - elasticsearch

networks:
  default:
    external:
      name: docker
