filebeat.config.inputs:
  enabled: true
  path: config/*.yml
  reload.enabled: true
  reload.period: 60s

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "filebeat-%{[agent.version]}-%{[input.type]}-%{+yyyy.MM.dd}"

processors:
  - drop_fields:
      ignore_missing: true
      fields:
        [
          "agent.ephemeral_id",
          "agent.hostname",
          "agent.id",
          "agent.type",
          "ecs",
          "event",
          "host",
        ]

setup.ilm.enabled: false
monitoring.enabled: true

logging.level: info
logging.json: true
logging.metrics.enabled: false
