# https://github.com/VictoriaMetrics/VictoriaMetrics
version: "3.8"

services:
  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:latest
    restart: unless-stopped
    command:
      - "--storageDataPath=/storage"
      - "--graphiteListenAddr=:2003"
      - "--opentsdbListenAddr=:4242"
      - "--httpListenAddr=:8428"
      - "--search.latencyOffset=1s" # Data becomes available 1s after ingestion
      - "--retentionPeriod=1" # 1 Month
      - "--selfScrapeInterval=60s" # Collect internal metrics
      - "--promscrape.config=prometheus.yml"
    ports:
      - "2003:2003/udp" # Proxmox -> Collectd / Graphite
      - "4242:4242" # OPNsense -> Netdata / openTSDB
      - "8428:8428" # Home Assistant -> InfluxDB
    volumes:
      # - /mnt/hdd/AppData/VictoriaMetrics:/storage
      - ./data:/storage
      - ./prometheus.yml:/prometheus.yml
    environment:
      - STATPING_API_KEY
    labels:
      - "diun.enable=true"
      - "containermon.enable=true"

networks:
  default:
    external:
      name: docker
