# https://github.com/VictoriaMetrics/VictoriaMetrics
version: "3.8"

services:
  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:latest
    restart: unless-stopped
    command:
      - "--storageDataPath=/storage"
      - "--graphiteListenAddr=:2003"
      - "--opentsdbListenAddr=:4242"
      - "--httpListenAddr=:8428"
      - "--search.latencyOffset=1s"
      - "--retentionPeriod=1"
      # - "--prometheus.config=prometheus.yml"
    ports:
      - "2003:2003/udp"
      - "4242:4242"
    volumes:
      - /mnt/hdd/AppData/VictoriaMetrics:/storage
      - ./prometheus.yml:/prometheus.yml
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  default:
    external:
      name: docker
