# https://github.com/VictoriaMetrics/VictoriaMetrics
version: "3.8"

services:
  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:latest
    restart: unless-stopped
    command:
      - "--storageDataPath=/storage"
      - "--graphiteListenAddr=:2003"
      - "--opentsdbListenAddr=:4242"
      - "--httpListenAddr=:8428"
      - "--search.latencyOffset=1s" # Data becomes available 1s after ingestion
      - "--retentionPeriod=1" # 1 Month
      - "--selfScrapeInterval=60s" # Collect internal metrics
      - "--promscrape.config=prometheus.yml"
      - "-eula=true"
    ports:
      - "2003:2003/udp" # Proxmox (collectd and internal metrics)
      - "4242:4242" # OPNsense (netdata)
    volumes:
      - /mnt/hdd/AppData/VictoriaMetrics:/storage
      - ./prometheus.yml:/prometheus.yml
    environment:
      - STATPING_API_KEY
    labels:
      - "containermon.enable=true"
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  default:
    external:
      name: docker
