version: "3.7"

services:
  victoriametrics:
    container_name: victoriametrics
    image: "victoriametrics/victoria-metrics:latest"
    restart: unless-stopped
    command:
      - "--storageDataPath=/storage"
      - "--graphiteListenAddr=:2003"
      - "--opentsdbListenAddr=:4242"
      - "--httpListenAddr=:8428"
      - "--search.latencyOffset=1s"
      - "--retentionPeriod=1"
      # - "--promscrape.config=promscrape.yaml"
    volumes:
      - "./storage:/storage"
      - "./prom.yaml:/prom.yaml"
    labels:
      - "diun.enable=true"

networks:
  default:
    external:
      name: docker
