# https://github.com/portainer/portainer

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    extends:
      file: ../base.yml
      service: base
    expose:
      - "9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "wud.watch.digest=true"
      - "wud.tag.include=^lts$$"

include:
  - ../network.yml
