version: "3.7"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    network_mode: bridge
    restart: always
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    labels:
      - "diun.enable=true"

volumes:
  data:
