version: "3.7"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    restart: unless-stopped
    command: --admin-password-file /tmp/password
    expose:
      - "9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./password:/tmp/password"
      - "./data:/data"
    labels:
      - "diun.enable=true"
      - "traefik.enable=true"

networks:
  default:
    external:
      name: docker
