# https://github.com/portainer/portainer
version: "3.8"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    command: ["--admin-password=${PASSWORD}"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/data
    labels:
      - "traefik.enable=true"
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

networks:
  default:
    external:
      name: docker
