# https://github.com/netdata/netdata
version: "3.8"

services:
  netdata:
    container_name: netdata
    hostname: ubuntu-server
    image: netdata/netdata:latest
    restart: unless-stopped
    expose:
      - "19999"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./config:/etc/netdata:ro
      - /etc/os-release:/host/etc/os-release:ro
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /mnt:/mnt:ro
    environment:
      - VIRTUALIZATION=kvm
      - DOCKER_HOST=socket-proxy:2375
    labels:
      - "traefik.enable=true"
      - "containermon.enable=true"
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  default:
    external:
      name: docker
