# https://github.com/netdata/netdata

services:
  netdata:
    container_name: netdata
    hostname: ubuntu-server
    image: netdata/netdata:stable
    extends:
      file: ../base.yml
      service: base
    expose:
      - "19999"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      # - ./cache:/var/cache/netdata
      # - ./lib:/var/lib/netdata
      - ./config:/etc/netdata
      - /etc/os-release:/host/etc/os-release:ro
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /mnt:/mnt:ro
    environment:
      - VIRTUALIZATION=kvm
      - DOCKER_HOST=socket-proxy:2375
    labels:
      - "traefik.enable=true"

include:
  - ../network.yml
