# https://github.com/roflcoopter/viseron
version: "3.8"

services:
  viseron:
    container_name: viseron
    image: roflcoopter/viseron:latest
    restart: unless-stopped
    volumes:
      - ./config:/config
      - /mnt/hdd/AppData/Viseron:/recordings
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/dri
      - /dev/bus/usb:/dev/bus/usb
    labels:
      - "diun.enable=true"

networks:
  default:
    external:
      name: docker
