# https://docs.docker.com/reference/compose-file/

services:
  stirling-pdf:
    container_name: stirling-pdf
    # https://docs.stirlingpdf.com/Installation/Versions/
    # 600MB RAM vs 300 MB RAM on lite
    image: docker.stirlingpdf.com/stirlingtools/stirling-pdf:1.1.1-ultra-lite
    extends:
      file: ../base.yml
      service: base
    expose:
      - "8080"
    volumes:
      - ./data/trainingData:/usr/share/tessdata
      - ./data/extraConfigs:/configs
      - ./data/customFiles:/customFiles/
      - ./data/logs:/logs/
      - ./data/pipeline:/pipeline/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - DISABLE_ADDITIONAL_FEATURES=true
      - LANGS=en_GB
    labels:
      - "traefik.enable=true"
      - "wud.tag.include=^\\d+\\.\\d+\\.\\d+.*$$"
      - "wud.tag.transform=^(\\d+\\.\\d+\\.\\d+).*$$ => $$1"

include:
  - ../network.yml
