# https://github.com/Stirling-Tools/Stirling-PDF

services:
  stirling-pdf:
    container_name: stirling-pdf
    # https://docs.stirlingpdf.com/Installation/Versions/
    # 600MB RAM vs 300 MB RAM on lite
    image: ghcr.io/stirling-tools/stirling-pdf:1.3.2-ultra-lite
    extends:
      file: ../base.yml
      service: base
    expose:
      - "8080"
    volumes:
      - ./data/trainingData:/usr/share/tessdata
      - ./data/extraConfigs:/configs
      - ./data/customFiles:/customFiles/
      - ./data/logs:/logs/
      - ./data/pipeline:/pipeline/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - DISABLE_ADDITIONAL_FEATURES=true
      - LANGS=en_GB
    labels:
      - "traefik.enable=true"
      # override hostname to just 'pdf'
      - "traefik.http.routers.stirling-pdf.rule=HostRegexp(`^pdf\\..+`)"
      - "traefik.http.services.stirling-pdf.loadbalancer.server.port=8080"
      - "wud.tag.include=^\\d+\\.\\d+\\.\\d+.*$$"
      - "wud.tag.transform=^(\\d+\\.\\d+\\.\\d+).*$$ => $$1"

include:
  - ../network.yml
