# https://github.com/Requarks/wiki
version: "3.8"

services:
  wikijs:
    container_name: wikijs
    image: requarks/wiki:2
    restart: unless-stopped
    expose:
      - "3000"
    depends_on:
      - wikijs-db
    volumes:
      - ./config.yml:/wiki/config.yml
      - ${HOME}/workspace/Notes:/notes
    environment:
      - DB_TYPE=postgres
      - DB_HOST=wikijs-db
      - DB_PORT=5432
      - DB_USER=wikijs
      - DB_PASS
      - DB_NAME=wiki
    labels:
      - "traefik.enable=true"
      - "containermon.enable=true"
      - "com.centurylinklabs.watchtower.enable=true"

  wikijs-db:
    container_name: wikijs-db
    image: postgres:11-alpine
    restart: unless-stopped
    logging:
      driver: "none"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=wiki
      - POSTGRES_PASSWORD
      - POSTGRES_USER=wikijs

networks:
  default:
    external:
      name: docker
