# https://github.com/Finsys/dockhand
services:
  dockhand:
    container_name: dockhand
    image: fnsys/dockhand:v1.0.46
    extends:
      file: ../base.yml
      service: base
    expose:
      - "3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # start / stop / create
      - ./data:/app/data
    labels:
      - "traefik.enable=true"
      - "wud.watch.digest=true"
      - "wud.tag.include=^v\\d+\\.\\d+\\.\\d+$$"

include:
  - ../network.yml
